name: LittleMonster
main: com.smallaswater.littlemonster.LittleMonsterMainClass
version: "NKMOT-1.8.0"
authors:
  - 若水
  - LT_Name
api: 1.0.13
softdepend:
  - "MemoriesOfTime-GameCore"
  - "RcRPG"
  - "MagicItem"
