name: LittleMonster
main: com.smallaswater.littlemonster.LittleMonsterMainClass
version: "1.7.1-SNAPSHOT"
authors:
  - 若水
  - LT_Name
api: 1.0.13
softdepend:
  - "MemoriesOfTime-GameCore"
  - "RcRPG"
  - "MagicItem"
